name: On Tag, Trigger GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-release-workflow:
    uses: harmony-labs/workflow-simple-release/.github/workflows/workflow.yaml@82c7409f5a02457b7214adf330f73237ef7b4121 # v1.0.0
    with:
      tag_name: ${{ github.ref_name }}
      release_name: ${{ github.ref_name }}
      draft: false
      prerelease: false