name: On Tag, Trigger GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-release-workflow:
    uses: harmony-labs/workflow-simple-release/.github/workflows/workflow.yaml@7dd07b3c0cc62f05dd1936d9cf9a37cd5e4f48aa # v0.1.1
    with:
      tag_name: ${{ github.ref_name }}
      release_name: ${{ github.ref_name }}
      draft: false
      prerelease: false